name: Custom Workflow
on:
  workflow_dispatch:

env:
  DIA_DE_LA_SEMANA: Lunes

jobs:
  Saludo_variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
    - name: Echo de saludo y nombre
      run: echo "${{ env.SALUDO }} ${{ vars.NOMBRE }}, hoy es $DIA_DE_LA_SEMANA"
  Saludo_secretos:
    runs-on: ubuntu-latest
    steps:
    - name: Echo de saludo con secreto
      run: echo "$SALUDO ${{ vars.NOMBRE }}, tu contraseña secreta es ${{ secrets.CONTRASENA }}"